### ISSUE TITLE
wifi setup screen in card layout should contain next/skip buttons within the card itself

### ISSUE THREAD

**Issue by jiteshsingh** [GrapheneOS/platform_packages_apps_SetupWizard2#12]
needs more changes (probably wider changes) to settings app in order to fix this UI issue.

**Comment by jiteshsingh** [comment]
can be closed with: https://github.com/GrapheneOS/os-issue-tracker/issues/3263

**Comment by matchboxbananasynergy** [comment]
@jiteshsingh Now that https://github.com/GrapheneOS/os-issue-tracker/issues/3263 is merged, is this definitely resolved and should be closed?

**Comment by jiteshsingh** [comment]
yes. closing now.
