### ISSUE TITLE
Possible missing text in fingerprint setup screen

### ISSUE THREAD

**Issue by matchboxbananasynergy** [GrapheneOS/platform_packages_apps_SetupWizard2#14]
On the "Set up fingerprint unlock" screen that provides details about how fingerprints work, on the last subsection named "Keep in mind", there are two paragraphs, and then there is a chain link icon with no text next to it.

I'd imagine if something is missing here, the issue is upstream as I don't believe this screen is ours. That said, it is worth exploring and confirming.

**Comment by jiteshsingh** [comment]
the corresponding string resource is empty at upstream.

- https://android.googlesource.com/platform/packages/apps/Settings/+/master/res/values/strings.xml#831
- https://github.com/GrapheneOS/platform_packages_apps_Settings/blob/14/res/values/strings.xml#L843

I see the stock pixel screen shows [this link](https://g.co/pixel/fingerprintunlock).
so we can either hide the row if empty or add an appropriate link.

**Comment by matchboxbananasynergy** [comment]
Looks like https://github.com/GrapheneOS/adevtool/pull/118 will resolve this.

Commit: https://github.com/GrapheneOS/adevtool/pull/118/commits/fd2198ad76055a289aba304e03921a1a1edb18d6
