### ISSUE TITLE
Explore whether adding a QR code scanning option in the Wi-Fi setup screen is possible

### ISSUE THREAD

**Issue by matchboxbananasynergy** [GrapheneOS/platform_packages_apps_SetupWizard2#22]
In the Wi-Fi setup screen, there could a QR scanning button to be able to add the Wi-Fi network in that way, simplifying setup. This is likely only desirable if it's simple to implement and maintain.

**Comment by jiteshsingh** [comment]
the feature exists already, but in a different way.
QR scanner button is available in the "Add network" activity (the activity that comes up after clicking on "+  Add network" button).

**Comment by matchboxbananasynergy** [comment]
Ah, apologies!
