### ISSUE TITLE
Face login setup has overflowing strings in card layout

### ISSUE THREAD

**Issue by matchboxbananasynergy** [GrapheneOS/platform_packages_apps_SetupWizard2#3]
this is an upstream bug (part of android settings app). we need to decide whether we want to modify the same.

**Comment by matchboxbananasynergy** [comment]
@jiteshsingh If this only applies to face unlock, it might not make sense to address it (given that it's an upstream issue) because we don't support face unlock on any supported device. It was supported for 4th gen Pixels but those are on their way out, and we don't support it on 7th and 8th gen Pixels due to considering it insecure.

If our users aren't going to see the affected screen, it sounds like it might not matter that this bug exists?

Thoughts? cc @muhomorr

**Comment by jiteshsingh** [comment]
yep I had this thought, maybe we can just skip (disable) that screen.
had some discussion with hulk few days ago.

**Comment by jiteshsingh** [comment]
not an issue anymore since the card layout has been gotten rid of
https://github.com/GrapheneOS/os-issue-tracker/issues/3263
